version: '3.1'

services:
  postgres:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=soundfuse
      - POSTGRES_PASSWORD=awesomemusicstuff
      - POSTGRES_DB=soundfuse

  redis:
    image:
      redis:6
    restart: always
    ports:
      - "6379:6379"